# Generated by Django 3.1 on 2020-10-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0003_auto_20201001_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
    ]
