# Generated by Django 3.1 on 2020-10-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0006_auto_20201002_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='section',
        ),
    ]
